In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('4strains_wreps.xlsx', sheet_name='YPD_30C', engine='openpyxl')
df
time = df.loc[:, df.columns.str.contains('Time')]
df = df.loc[:, ~df.iloc[0].isna()]
df.columns = df.iloc[0]
df = df.drop(index=0)
df

,Rep1,Rep1 Average,Rep2,Rep 2 Average,Rep1,Rep2 Average,Rep2,Rep3 Average,Rep1,Rep1 Average,...,Rep3,Rep2 Average,Rep1,Rep1 Average,Rep2,Rep2 Average,Rep1,Rep1 Average,Rep2,Rep2 Average
1,-0.000833,-0.000333,-0.0004,0.0051,-0.001833,0.0015,0.0036,0.005767,-0.003567,-0.000667,...,-0.00786,0.01134,-0.005833,-0.001,0.0016,0.0006,-0.003833,-0.038333,0.0006,0.005433
2,-0.000333,0.000167,-0.0004,0.005267,-0.001333,0.001667,0.0036,0.004933,-0.004567,-0.002468,...,-0.00786,0.00774,-0.005333,-0.000833,0.0016,0.000933,-0.004333,-0.038167,0.0006,0.0056
3,-0.001,-0.0005,0.0002,0.005533,0.003,0.002,0.0042,0.0052,-0.003567,-0.002168,...,-0.00786,0.00614,-0.005,-0.000667,0.0022,0.000867,-0.004,-0.0385,0.0012,0.005867
4,-0.001667,-0.000417,0.0004,0.0059,0.007333,0.003333,0.0024,0.005233,-0.003567,-0.002468,...,-0.00786,0.00514,-0.004667,-0.000667,0.0024,0.001067,-0.003667,-0.038,0.0014,0.006067
5,-0.000833,0.000167,0.0014,0.006567,0.011167,0.004333,0.0024,0.005233,-0.003567,-0.002068,...,-0.00686,0.00514,-0.004833,-0.0005,0.0024,0.001233,-0.003833,-0.038,0.0014,0.006233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,1.230167,1.239167,1.1904,1.202067,1.029167,1.0455,1.0364,1.024233,0.916433,0.901433,...,1.140139,1.144539,1.119167,1.092833,1.0974,1.078067,1.299167,1.277,1.3194,1.3039
69,1.228833,1.238083,1.1894,1.201567,1.026833,1.044167,1.0354,1.022567,0.914933,0.900033,...,1.138139,1.142939,1.116833,1.091333,1.0964,1.0769,1.298833,1.276667,1.3184,1.303233
70,1.228167,1.237417,1.1884,1.200567,1.025167,1.042333,1.0334,1.0204,0.912933,0.898733,...,1.136139,1.141339,1.116167,1.090333,1.0944,1.075233,1.297167,1.275667,1.3184,1.302733
71,1.227333,1.236833,1.1864,1.199567,1.024333,1.041667,1.0314,1.0189,0.911933,0.897733,...,1.134139,1.139539,1.115333,1.089167,1.0924,1.0739,1.297333,1.275167,1.3174,1.3024
72,1.2275,1.237,1.1862,1.199533,1.0245,1.041333,1.0302,1.017533,0.910933,0.896633,...,1.133139,1.138139,1.1145,1.088833,1.0912,1.073033,1.2965,1.2755,1.3162,1.301867

In [3]:
time
time = time.drop(time.index[0]).reset_index(drop=True)
time
print(len(df))

72

In [4]:
df = df.loc[:, df.columns.str.contains('Average')]
df.head()
df.index = time['Time']
df

,Rep1 Average,Rep 2 Average,Rep2 Average,Rep3 Average,Rep1 Average,Rep2 Average,Rep3 Average,Rep1 Average,Rep2 Average,Rep3 Average,Rep1 Average,Rep2 Average,Rep2 Average,Rep1 Average,Rep2 Average,Rep1 Average,Rep2 Average
Time,,,,,,,,,,,,,,,,,
0.333334,-0.000333,0.0051,0.0015,0.005767,-0.000667,0.008203,0.003339,-0.000467,0.007603,0.01034,0.000733,0.008403,0.01134,-0.001,0.0006,-0.038333,0.005433
0.666667,0.000167,0.005267,0.001667,0.004933,-0.002468,0.006803,0.00034,-0.002367,0.006203,0.00694,-0.000869,0.006803,0.00774,-0.000833,0.000933,-0.038167,0.0056
1.000000,-0.0005,0.005533,0.002,0.0052,-0.002168,0.006403,-0.00066,-0.002867,0.005803,0.00614,-0.000569,0.006803,0.00614,-0.000667,0.000867,-0.0385,0.005867
1.333333,-0.000417,0.0059,0.003333,0.005233,-0.002468,0.006603,-0.00106,-0.002967,0.006003,0.00534,-0.000368,0.007003,0.00514,-0.000667,0.001067,-0.038,0.006067
1.666667,0.000167,0.006567,0.004333,0.005233,-0.002068,0.007203,-0.00166,-0.002367,0.006603,0.00514,0.000332,0.007803,0.00514,-0.0005,0.001233,-0.038,0.006233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22.666670,1.239167,1.202067,1.0455,1.024233,0.901433,0.847403,0.960539,1.036633,0.983003,1.071739,1.207933,1.170203,1.144539,1.092833,1.078067,1.277,1.3039
23.000000,1.238083,1.201567,1.044167,1.022567,0.900033,0.846603,0.958939,1.035033,0.983403,1.071339,1.208633,1.170203,1.142939,1.091333,1.0769,1.276667,1.303233
23.333340,1.237417,1.200567,1.042333,1.0204,0.898733,0.846603,0.957939,1.033833,0.984203,1.070739,1.208933,1.170403,1.141339,1.090333,1.075233,1.275667,1.302733
23.666670,1.236833,1.199567,1.041667,1.0189,0.897733,0.846603,0.956539,1.033033,0.984803,1.069339,1.208933,1.170603,1.139539,1.089167,1.0739,1.275167,1.3024
24.000000,1.237,1.199533,1.041333,1.017533,0.896633,0.846203,0.955139,1.032033,0.985003,1.068939,1.208833,1.170603,1.138139,1.088833,1.073033,1.2755,1.301867

In [5]:
df.columns.values[2] = 'Rep 1 Average'
df.columns.values[3] = 'Rep 2 Average'
df.columns = [
    'D1 ' + df.columns[0],
    'D1 ' + df.columns[1],
    'AE2 ' + df.columns[2],
    'AE2 ' + df.columns[3],
    '110 ' + df.columns[4],
    '110 ' + df.columns[5],
    '110 ' + df.columns[6],
    '111 ' + df.columns[7],
    '111 ' + df.columns[8],
    '111 ' + df.columns[9],
    '112 ' + df.columns[10],
    '112 ' + df.columns[11],
    '112 ' + df.columns[12],
    'CBS138 ' + df.columns[13],
    'CBS138 ' + df.columns[14],
    'BG2 ' + df.columns[15],
    'BG2 ' + df.columns[16]
]
df.head()
df.columns.values[12] = '112 Rep3 Average'
df.head()

,D1 Rep1 Average,D1 Rep 2 Average,AE2 Rep 1 Average,AE2 Rep 2 Average,110 Rep1 Average,110 Rep2 Average,110 Rep3 Average,111 Rep1 Average,111 Rep2 Average,111 Rep3 Average,112 Rep1 Average,112 Rep2 Average,112 Rep3 Average,CBS138 Rep1 Average,CBS138 Rep2 Average,BG2 Rep1 Average,BG2 Rep2 Average
Time,,,,,,,,,,,,,,,,,
0.333334,-0.000333,0.0051,0.0015,0.005767,-0.000667,0.008203,0.003339,-0.000467,0.007603,0.01034,0.000733,0.008403,0.01134,-0.001,0.0006,-0.038333,0.005433
0.666667,0.000167,0.005267,0.001667,0.004933,-0.002468,0.006803,0.00034,-0.002367,0.006203,0.00694,-0.000869,0.006803,0.00774,-0.000833,0.000933,-0.038167,0.0056
1.000000,-0.0005,0.005533,0.002,0.0052,-0.002168,0.006403,-0.00066,-0.002867,0.005803,0.00614,-0.000569,0.006803,0.00614,-0.000667,0.000867,-0.0385,0.005867
1.333333,-0.000417,0.0059,0.003333,0.005233,-0.002468,0.006603,-0.00106,-0.002967,0.006003,0.00534,-0.000368,0.007003,0.00514,-0.000667,0.001067,-0.038,0.006067
1.666667,0.000167,0.006567,0.004333,0.005233,-0.002068,0.007203,-0.00166,-0.002367,0.006603,0.00514,0.000332,0.007803,0.00514,-0.0005,0.001233,-0.038,0.006233

In [6]:
df.to_excel('prcsd_YPD30.xlsx')