In [1]:
import numpy as np
import pandas as pd

In [61]:
df = pd.read_excel('Trial 2.xlsx', sheet_name='YPD_37C')
time = df.loc[:, df.columns.str.contains('Time')]
df = df.loc[:, ~df.iloc[0].isna()]
df.columns = df.iloc[0]
df
time = time.drop(time.index[0]).reset_index(drop=True)

In [62]:
df = df.drop(df.index[0]).reset_index(drop=True)
df = df.loc[:, df.columns.str.contains('Average')]
df.head()
df.index = time['Time']
df

,Rep1 Average,Rep 2 Average,Rep 3 Average,Rep1 Average,Rep2 Average,Rep3 Average,Rep1 Average,Rep2 Average,Rep3 Average,Rep1 Average,...,Rep2 Average,Rep3 Average,Rep4 Average,Rep5 Average,Rep6 Average,Rep1 Average,Rep2 Average,Rep3 Average,Rep4 Average,Rep5 Average
Time,,,,,,,,,,,,,,,,,,,,,
0.333334,0.003875,0.00175,0.001,0.00175,0.00375,0.005667,0.013582,0.004768,0.005125,0.008249,...,0.001625,0.004417,-0.001569,0.006768,0.002126,0.023584,0.0038,0.003,0.008248,0.004327
0.666667,0.003875,0.002333,0.001833,0.002375,0.00425,0.006167,0.011998,0.003868,0.003325,0.006415,...,0.001625,0.005333,-0.00357,0.005568,0.000726,0.024117,0.0049,0.003667,0.005915,0.002994
1.000000,0.00425,0.00225,0.0015,0.002875,0.004333,0.005833,0.011665,0.003468,0.002525,0.006499,...,0.002125,0.00525,-0.00377,0.004768,0.000326,0.025083,0.0047,0.003833,0.004915,0.002605
1.333333,0.005,0.002417,0.002,0.003375,0.00425,0.006167,0.012082,0.003368,0.002325,0.007082,...,0.002375,0.005667,-0.00417,0.004368,0.000326,0.027442,0.0049,0.004667,0.004748,0.002605
1.666667,0.005625,0.003,0.002667,0.00375,0.005083,0.006833,0.012915,0.003468,0.003125,0.007832,...,0.00275,0.006,-0.00387,0.004368,0.000326,0.03175,0.0058,0.005667,0.005748,0.002772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22.666670,1.199,1.143833,1.170667,0.951625,0.89525,0.92,0.903332,0.960168,0.951325,1.032165,...,1.012625,0.963917,1.047533,1.080368,1.084925,1.155567,1.2012,1.220333,1.226415,1.264993
23.000000,1.20575,1.143083,1.169667,0.951375,0.893833,0.918667,0.901665,0.958068,0.949125,1.054165,...,1.0125,0.962667,1.045333,1.079368,1.082725,1.155559,1.2006,1.2185,1.224581,1.265104
23.333340,1.211375,1.142083,1.169333,0.95,0.892167,0.917333,0.898733,0.956368,0.948125,1.033833,...,1.01175,0.961417,1.043833,1.078068,1.081925,1.230187,1.2004,1.218,1.223033,1.265438
23.666670,1.217625,1.141083,1.168333,0.94925,0.8905,0.9155,0.897733,0.954868,0.946325,1.033033,...,1.01125,0.96,1.042333,1.077468,1.079525,1.232063,1.2,1.216833,1.222033,1.265993
24.000000,1.217625,1.139833,1.167333,0.94925,0.888583,0.914333,0.896633,0.953168,0.944925,1.032033,...,NaN,0.95875,1.040633,1.076668,1.078325,NaN,1.1995,1.215667,1.221933,1.265993

In [63]:
new_columns = (
    ['D1 ' + col for col in df.columns[:3]] +
    ['AE2 ' + col for col in df.columns[3:6]] +
    ['110 ' + col for col in df.columns[6:9]] +
    ['111 ' + col for col in df.columns[9:12]] +
    ['112 ' + col for col in df.columns[12:14]] +
    ['CBS138 ' + col for col in df.columns[14:20]] +
    ['BG2 ' + col for col in df.columns[20:25]]
)
df.columns = new_columns
df.head()

#do NOT run again

,D1 Rep1 Average,D1 Rep 2 Average,D1 Rep 3 Average,AE2 Rep1 Average,AE2 Rep2 Average,AE2 Rep3 Average,110 Rep1 Average,110 Rep2 Average,110 Rep3 Average,111 Rep1 Average,...,CBS138 Rep2 Average,CBS138 Rep3 Average,CBS138 Rep4 Average,CBS138 Rep5 Average,CBS138 Rep6 Average,BG2 Rep1 Average,BG2 Rep2 Average,BG2 Rep3 Average,BG2 Rep4 Average,BG2 Rep5 Average
Time,,,,,,,,,,,,,,,,,,,,,
0.333334,0.003875,0.00175,0.001,0.00175,0.00375,0.005667,0.013582,0.004768,0.005125,0.008249,...,0.001625,0.004417,-0.001569,0.006768,0.002126,0.023584,0.0038,0.003,0.008248,0.004327
0.666667,0.003875,0.002333,0.001833,0.002375,0.00425,0.006167,0.011998,0.003868,0.003325,0.006415,...,0.001625,0.005333,-0.00357,0.005568,0.000726,0.024117,0.0049,0.003667,0.005915,0.002994
1.000000,0.00425,0.00225,0.0015,0.002875,0.004333,0.005833,0.011665,0.003468,0.002525,0.006499,...,0.002125,0.00525,-0.00377,0.004768,0.000326,0.025083,0.0047,0.003833,0.004915,0.002605
1.333333,0.005,0.002417,0.002,0.003375,0.00425,0.006167,0.012082,0.003368,0.002325,0.007082,...,0.002375,0.005667,-0.00417,0.004368,0.000326,0.027442,0.0049,0.004667,0.004748,0.002605
1.666667,0.005625,0.003,0.002667,0.00375,0.005083,0.006833,0.012915,0.003468,0.003125,0.007832,...,0.00275,0.006,-0.00387,0.004368,0.000326,0.03175,0.0058,0.005667,0.005748,0.002772

In [64]:
df.head()

,D1 Rep1 Average,D1 Rep 2 Average,D1 Rep 3 Average,AE2 Rep1 Average,AE2 Rep2 Average,AE2 Rep3 Average,110 Rep1 Average,110 Rep2 Average,110 Rep3 Average,111 Rep1 Average,...,CBS138 Rep2 Average,CBS138 Rep3 Average,CBS138 Rep4 Average,CBS138 Rep5 Average,CBS138 Rep6 Average,BG2 Rep1 Average,BG2 Rep2 Average,BG2 Rep3 Average,BG2 Rep4 Average,BG2 Rep5 Average
Time,,,,,,,,,,,,,,,,,,,,,
0.333334,0.003875,0.00175,0.001,0.00175,0.00375,0.005667,0.013582,0.004768,0.005125,0.008249,...,0.001625,0.004417,-0.001569,0.006768,0.002126,0.023584,0.0038,0.003,0.008248,0.004327
0.666667,0.003875,0.002333,0.001833,0.002375,0.00425,0.006167,0.011998,0.003868,0.003325,0.006415,...,0.001625,0.005333,-0.00357,0.005568,0.000726,0.024117,0.0049,0.003667,0.005915,0.002994
1.000000,0.00425,0.00225,0.0015,0.002875,0.004333,0.005833,0.011665,0.003468,0.002525,0.006499,...,0.002125,0.00525,-0.00377,0.004768,0.000326,0.025083,0.0047,0.003833,0.004915,0.002605
1.333333,0.005,0.002417,0.002,0.003375,0.00425,0.006167,0.012082,0.003368,0.002325,0.007082,...,0.002375,0.005667,-0.00417,0.004368,0.000326,0.027442,0.0049,0.004667,0.004748,0.002605
1.666667,0.005625,0.003,0.002667,0.00375,0.005083,0.006833,0.012915,0.003468,0.003125,0.007832,...,0.00275,0.006,-0.00387,0.004368,0.000326,0.03175,0.0058,0.005667,0.005748,0.002772

In [69]:
NaN_fix = df[['CBS138 Rep1 Average', 'CBS138 Rep2 Average', 'BG2 Rep1 Average']]
NaN_fix.to_excel('NaN_fix.xlsx')